import { v4 } from "uuid";

type JobCategory = "it" | "sales" | "managment";
type JobType = "cdi" | "cdd" | "internship";

interface Job {
  uuid: string;
  title: string;
  category: JobCategory;
  type: JobType;
  salary: number;
  createdAt: Date;
}

export const jobs: Job[] = [
  {
    uuid: v4(),
    title: "Senior Full Stack Developer",
    category: "it",
    type: "cdi",
    salary: 65000,
    createdAt: new Date("2025-10-01"),
  },
  {
    uuid: v4(),
    title: "Sales Manager",
    category: "sales",
    type: "cdi",
    salary: 55000,
    createdAt: new Date("2025-10-02"),
  },
  {
    uuid: v4(),
    title: "Product Manager",
    category: "managment",
    type: "cdi",
    salary: 70000,
    createdAt: new Date("2025-10-03"),
  },
  {
    uuid: v4(),
    title: "Frontend Developer",
    category: "it",
    type: "cdd",
    salary: 45000,
    createdAt: new Date("2025-10-04"),
  },
  {
    uuid: v4(),
    title: "Business Development Representative",
    category: "sales",
    type: "cdi",
    salary: 42000,
    createdAt: new Date("2025-10-05"),
  },
  {
    uuid: v4(),
    title: "IT Support Specialist",
    category: "it",
    type: "internship",
    salary: 18000,
    createdAt: new Date("2025-10-06"),
  },
  {
    uuid: v4(),
    title: "DevOps Engineer",
    category: "it",
    type: "cdi",
    salary: 62000,
    createdAt: new Date("2025-10-07"),
  },
  {
    uuid: v4(),
    title: "Sales Executive",
    category: "sales",
    type: "cdd",
    salary: 38000,
    createdAt: new Date("2025-10-08"),
  },
  {
    uuid: v4(),
    title: "Project Manager",
    category: "managment",
    type: "cdi",
    salary: 68000,
    createdAt: new Date("2025-10-09"),
  },
  {
    uuid: v4(),
    title: "Data Analyst",
    category: "it",
    type: "cdi",
    salary: 52000,
    createdAt: new Date("2025-10-10"),
  },
  {
    uuid: v4(),
    title: "Account Manager",
    category: "sales",
    type: "cdi",
    salary: 50000,
    createdAt: new Date("2025-10-11"),
  },
  {
    uuid: v4(),
    title: "Operations Manager",
    category: "managment",
    type: "cdi",
    salary: 65000,
    createdAt: new Date("2025-10-12"),
  },
  {
    uuid: v4(),
    title: "Backend Developer",
    category: "it",
    type: "cdi",
    salary: 58000,
    createdAt: new Date("2025-10-13"),
  },
  {
    uuid: v4(),
    title: "Sales Intern",
    category: "sales",
    type: "internship",
    salary: 15000,
    createdAt: new Date("2025-10-14"),
  },
  {
    uuid: v4(),
    title: "HR Manager",
    category: "managment",
    type: "cdi",
    salary: 60000,
    createdAt: new Date("2025-10-15"),
  },
  {
    uuid: v4(),
    title: "Mobile Developer",
    category: "it",
    type: "cdd",
    salary: 48000,
    createdAt: new Date("2025-09-28"),
  },
  {
    uuid: v4(),
    title: "Regional Sales Director",
    category: "sales",
    type: "cdi",
    salary: 75000,
    createdAt: new Date("2025-09-27"),
  },
  {
    uuid: v4(),
    title: "IT Intern",
    category: "it",
    type: "internship",
    salary: 16000,
    createdAt: new Date("2025-09-26"),
  },
  {
    uuid: v4(),
    title: "Scrum Master",
    category: "managment",
    type: "cdi",
    salary: 62000,
    createdAt: new Date("2025-09-25"),
  },
  {
    uuid: v4(),
    title: "Cloud Architect",
    category: "it",
    type: "cdi",
    salary: 80000,
    createdAt: new Date("2025-09-24"),
  },
  {
    uuid: v4(),
    title: "Insuuide Sales Representative",
    category: "sales",
    type: "cdd",
    salary: 35000,
    createdAt: new Date("2025-09-23"),
  },
  {
    uuid: v4(),
    title: "QA Engineer",
    category: "it",
    type: "cdi",
    salary: 50000,
    createdAt: new Date("2025-09-22"),
  },
  {
    uuid: v4(),
    title: "Business Analyst",
    category: "managment",
    type: "cdi",
    salary: 56000,
    createdAt: new Date("2025-09-21"),
  },
  {
    uuid: v4(),
    title: "Security Engineer",
    category: "it",
    type: "cdi",
    salary: 72000,
    createdAt: new Date("2025-09-20"),
  },
  {
    uuid: v4(),
    title: "Sales Coordinator",
    category: "sales",
    type: "cdd",
    salary: 32000,
    createdAt: new Date("2025-09-19"),
  },
  {
    uuid: v4(),
    title: "Team Lead",
    category: "managment",
    type: "cdi",
    salary: 66000,
    createdAt: new Date("2025-09-18"),
  },
  {
    uuid: v4(),
    title: "Database Administrator",
    category: "it",
    type: "cdi",
    salary: 60000,
    createdAt: new Date("2025-09-17"),
  },
  {
    uuid: v4(),
    title: "Key Account Manager",
    category: "sales",
    type: "cdi",
    salary: 58000,
    createdAt: new Date("2025-09-16"),
  },
  {
    uuid: v4(),
    title: "Management Intern",
    category: "managment",
    type: "internship",
    salary: 17000,
    createdAt: new Date("2025-09-15"),
  },
  {
    uuid: v4(),
    title: "Software Engineer",
    category: "it",
    type: "cdi",
    salary: 60000,
    createdAt: new Date("2025-09-14"),
  },
  {
    uuid: v4(),
    title: "Sales Trainer",
    category: "sales",
    type: "cdi",
    salary: 48000,
    createdAt: new Date("2025-09-13"),
  },
  {
    uuid: v4(),
    title: "Chief Technology Officer",
    category: "managment",
    type: "cdi",
    salary: 95000,
    createdAt: new Date("2025-09-12"),
  },
  {
    uuid: v4(),
    title: "UI/UX Designer",
    category: "it",
    type: "cdd",
    salary: 46000,
    createdAt: new Date("2025-09-11"),
  },
  {
    uuid: v4(),
    title: "Channel Sales Manager",
    category: "sales",
    type: "cdi",
    salary: 62000,
    createdAt: new Date("2025-09-10"),
  },
  {
    uuid: v4(),
    title: "Network Engineer",
    category: "it",
    type: "cdi",
    salary: 55000,
    createdAt: new Date("2025-09-09"),
  },
  {
    uuid: v4(),
    title: "Department Manager",
    category: "managment",
    type: "cdi",
    salary: 64000,
    createdAt: new Date("2025-09-08"),
  },
  {
    uuid: v4(),
    title: "Data Scientist",
    category: "it",
    type: "cdi",
    salary: 70000,
    createdAt: new Date("2025-09-07"),
  },
  {
    uuid: v4(),
    title: "Pre-Sales Consultant",
    category: "sales",
    type: "cdd",
    salary: 44000,
    createdAt: new Date("2025-09-06"),
  },
  {
    uuid: v4(),
    title: "Systems Administrator",
    category: "it",
    type: "cdi",
    salary: 52000,
    createdAt: new Date("2025-09-05"),
  },
  {
    uuid: v4(),
    title: "Sales Operations Manager",
    category: "sales",
    type: "cdi",
    salary: 60000,
    createdAt: new Date("2025-09-04"),
  },
  {
    uuid: v4(),
    title: "Program Manager",
    category: "managment",
    type: "cdi",
    salary: 72000,
    createdAt: new Date("2025-09-03"),
  },
  {
    uuid: v4(),
    title: "Machine Learning Engineer",
    category: "it",
    type: "cdi",
    salary: 75000,
    createdAt: new Date("2025-09-02"),
  },
  {
    uuid: v4(),
    title: "Technical Sales Engineer",
    category: "sales",
    type: "cdi",
    salary: 64000,
    createdAt: new Date("2025-09-01"),
  },
  {
    uuid: v4(),
    title: "IT Project Manager",
    category: "managment",
    type: "cdi",
    salary: 68000,
    createdAt: new Date("2025-08-31"),
  },
  {
    uuid: v4(),
    title: "Site Reliability Engineer",
    category: "it",
    type: "cdi",
    salary: 68000,
    createdAt: new Date("2025-08-30"),
  },
  {
    uuid: v4(),
    title: "Business Development Manager",
    category: "sales",
    type: "cdi",
    salary: 66000,
    createdAt: new Date("2025-08-29"),
  },
  {
    uuid: v4(),
    title: "Engineering Manager",
    category: "managment",
    type: "cdi",
    salary: 82000,
    createdAt: new Date("2025-08-28"),
  },
  {
    uuid: v4(),
    title: "Full Stack Intern",
    category: "it",
    type: "internship",
    salary: 19000,
    createdAt: new Date("2025-08-27"),
  },
  {
    uuid: v4(),
    title: "Enterprise Sales Executive",
    category: "sales",
    type: "cdi",
    salary: 70000,
    createdAt: new Date("2025-08-26"),
  },
  {
    uuid: v4(),
    title: "Agile Coach",
    category: "managment",
    type: "cdd",
    salary: 58000,
    createdAt: new Date("2025-08-25"),
  },
];
